version: "3.8"

services:
  db:
    image: postgres:15
    container_name: daily_postgres
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: .
    container_name: daily_django
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/dm/static
      - media_volume:/dm/media
    env_file:
      - .env
    command: >
      bash -c "gunicorn dailyMenu.wsgi:application -b 0.0.0.0:8000"
    ports:
      - 8000:8000

#  nginx:
#    build:
#      dockerfile: ./Dockerfile
#      context: ./docker/nginx/
#    container_name: daily_nginx
#    image: dm_nginx
#    volumes:
#      - static_volume:/dm/static
#      - media_volume:/dm/media
#    depends_on:
#      - django
#    ports:
#      - \"${NGINX_EXTERNAL_PORT}:80/\"

volumes:
  static_volume:
  media_volume: