# Generated by Django 4.2.3 on 2023-07-10 16:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_des_menu_description_rename_name_menu_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=255),
        ),
    ]
