# Generated by Django 4.2.3 on 2023-07-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('dish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.menu')),
            ],
        ),
    ]
