# Generated by Django 4.2.3 on 2023-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.CharField(null=True),
        ),
    ]
