# Generated by Django 4.2.3 on 2023-07-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_order_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.menu'),
        ),
    ]
